export const myProjects =[
    {
        id: 1,
        category: ["react"],
        projectTitle: "React Project",
        projectSubTitle: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illo officiis obcaecati magni perspiciatis? Necessitatibus, saepe.",
        projectImage: "./images/1.jpg",
        projectLink: "",
        projectGithub: "https://github.com/zyadnasr",
    },
    {
        id: 2,
        category: ["react", "css"],
        projectTitle: "React & CSS Project",
        projectSubTitle: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illo officiis obcaecati magni perspiciatis? Necessitatibus, saepe.",
        projectImage: "./images/2.jpg",
        projectLink: "",
        projectGithub: "https://github.com/zyadnasr",
    },
    {
        id: 3,
        category: ["css"],
        projectTitle: "CSS Project",
        projectSubTitle: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illo officiis obcaecati magni perspiciatis? Necessitatibus, saepe.",
        projectImage: "./images/3.jpg",
        projectLink: "",
        projectGithub: "https://github.com/zyadnasr",
    },
    {
        id: 4,
        category: ["react"],
        projectTitle: "React Project",
        projectSubTitle: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illo officiis obcaecati magni perspiciatis? Necessitatibus, saepe.",
        projectImage: "./images/4.jpg",
        projectLink: "",
        projectGithub: "https://github.com/zyadnasr",
    },
    {
        id: 5,
        category: ["css"],
        projectTitle: "CSS Project",
        projectSubTitle: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illo officiis obcaecati magni perspiciatis? Necessitatibus, saepe.",
        projectImage: "./images/5.jpg",
        projectLink: "",
        projectGithub: "https://github.com/zyadnasr",
    },
    {
        id: 6,
        category: ["javascript"],
        projectTitle: "JavaScript Project",
        projectSubTitle: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illo officiis obcaecati magni perspiciatis? Necessitatibus, saepe.",
        projectImage: "./images/6.jpg",
        projectLink: "",
        projectGithub: "https://github.com/zyadnasr",
    },
    {
        id: 7,
        category: ["Node & Express"],
        projectTitle: "Node & Express Project",
        projectSubTitle: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illo officiis obcaecati magni perspiciatis? Necessitatibus, saepe.",
        projectImage: "./images/7.jpg",
        projectLink: "",
        projectGithub: "https://github.com/zyadnasr",
    },
    {
        id: 8,
        category: ["Node & Express"],
        projectTitle: "Node & Express Project",
        projectSubTitle: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illo officiis obcaecati magni perspiciatis? Necessitatibus, saepe.",
        projectImage: "./images/8.jpg",
        projectLink: "",
        projectGithub: "https://github.com/zyadnasr",
    },
    {
        id: 9,
        category: ["javascript"],
        projectTitle: "JavaScript Project",
        projectSubTitle: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illo officiis obcaecati magni perspiciatis? Necessitatibus, saepe.",
        projectImage: "./images/9.jpg",
        projectLink: "",
        projectGithub: "https://github.com/zyadnasr",
    },
]